CREATE TABLE [dbo].[LSOpportunityMeetingNotesApproval](
	[ApprovalID] [int] IDENTITY(1,1) NOT NULL,
	[ExternalMeetingID] [nvarchar](255) NOT NULL,
	[ExternalClientReferenceID] [nvarchar](255) NULL,
	[Status] [char](1) NOT NULL,
	[MeetingDate] [datetime] NULL,
	[MeetingTitle] [nvarchar](255) NULL,
	[MeetingSummary] [ntext] NULL,
	[TranscriptUrl] [nvarchar](2048) NULL,
	[OrganizerEmail] [nvarchar](255) NULL,
	[ParticipantEmails] [ntext] NULL,
	[SuggestedOpportunityID] [nvarchar](15) NULL,
	[ConfirmedOpportunityID] [nvarchar](15) NULL,
	[MatchDiagnostics] [ntext] NULL,
	[ErrorMessage] [ntext] NULL,
	[ActivityNoteID] [uniqueidentifier] NULL,
	[ApprovedByID] [uniqueidentifier] NULL,
	[ApprovedDateTime] [datetime] NULL,
	[NoteID] [uniqueidentifier] NULL,
	[CreatedByID] [uniqueidentifier] NULL,
	[CreatedByScreenID] [char](8) NULL,
	[CreatedDateTime] [datetime] NULL,
	[LastModifiedByID] [uniqueidentifier] NULL,
	[LastModifiedByScreenID] [char](8) NULL,
	[LastModifiedDateTime] [datetime] NULL,
	[tstamp] [timestamp] NOT NULL,
	CONSTRAINT [PK_LSOpportunityMeetingNotesApproval] PRIMARY KEY CLUSTERED ([ApprovalID] ASC)
);
